<?php $order = $this->getOrder();?>
<?php $order = $this->getOrder();?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Delivery Date'); ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label"><label><?php echo $this->__('Delivery Time');?></label></td>
                <td class="value"><strong><?php echo $this->__($order->getDeliveryTime());?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $this->__('Delivery Content');?></label></td>
                <td class="value"><strong><?php echo $this->__($order->getDeliveryContent());?></strong></td>
            </tr>
         </tbody></table>
    </div>
</div>