<?php $order = $this->getOrder();?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Invoice Information'); ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label"><label><?php echo $this->__('Invoice Type');?></label></td>
                <td class="value"><strong><?php echo $this->__($order->getBillType())?$this->__($order->getBillType()):'No Invoice'; ?></strong></td>
            </tr>
            <?php
            if ($order->getBillTitle() == 'Units') {
                $title = $order->getBillCompany();
            } else {
                $title =$order->getCustomerLastname() . $order->getCustomerFirstname() ;
            }
            ?>
            <tr>
                <td class="label"><label><?php echo $this->__('Invoices Payable');?></label></td>
                <td class="value"><strong><?php echo $this->__($title); ?></strong></td>
            </tr>

            <tr>
                <td class="label"><label><?php echo $this->__('Invoice Content');?></label></td>
                <td class="value"><strong><?php echo $this->__($order->getBillContent()); ?></strong></td>
            </tr>
<!--            --><?php //if ($order->getBillCompany()): ?>
<!--                <tr>-->
<!--                    <td class="label"><label>--><?php //echo $this->__('Units Name');?><!--</label></td>-->
<!--                    <td class="value"><strong>--><?php //echo $this->__($order->getBillCompany()); ?><!--</strong></td>-->
<!--                </tr>-->
<!--            --><?php //endif;?>
            <?php if ($order->getBillType() == 'VAT Invoice'): ?>
                <tr>
                    <td class="label"><label><?php echo $this->__('Taxpayer identification number');?></label></td>
                    <td class="value"><strong><?php echo $this->__($order->getBillTaxpayerId()); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Registered Address');?></label></td>
                    <td class="value"><strong><?php echo $this->__($order->getBillAddress()); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Registered Telephone');?></label></td>
                    <td class="value"><strong><?php echo $this->__($order->getBillPhone()); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Open an account with the bank');?></label></td>
                    <td class="value"><strong><?php echo $this->__($order->getBillBank()); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Bank account');?></label></td>
                    <td class="value"><strong><?php echo $this->__($order->getBillAccount()); ?></strong></td>
                </tr>
            <?php endif;?>
         </tbody></table>
    </div>
</div>