<style type="text/css">
     .form_list .fields span.required {color:red}
</style>
<div class="onepage_items order_message clearfix">
        <span><a id="bill-edit" href="javascript:void(0)"><?php echo $this->__('Change');?></a></span>
    </h4>

    <div class="clearbolck"></div>
    <label><input id="bill-switch" type="checkbox" value="1"/> <?php echo $this->__('Invoice');?></label>

    <div class="bill">
        <form id="bill-form">
            <ul class="form_list form-list">
                <li class="fields" style="height: auto;"><span class="label"><?php echo $this->__('Invoice Type');?>
                        ：</span>

                <input type="hidden" name="need_invoice" id="need_invoice" value="0"/>

                    <li class="control">
                    <input type="radio" name="bill_type"  value="General Invoice" checked="checked" title="General Invoice"  class="radio">
                    <label for="bill_type"><?php echo $this->__('General Invoice');?></label>

                    <input type="radio" name="bill_type"  value="VAT Invoice" title="VAT Invoice"  class="radio">
                    <label for="bill_type"><?php echo $this->__('VAT Invoice');?></label>
                    </li>

<!--                    <label><input name="bill_type" type="radio" value="0" checked="checked"/>--><?php //echo $this->__( 'General Invoice' );?><!--</label>-->
<!--                    <label><input name="bill_type" type="radio" value="1"/>--><?php //echo $this->__('VAT Invoice');?><!--</label>-->
                <li class="fields" style="height: auto;"><span class="label"><?php echo $this->__('Invoices Payable');?>
                        ：</span>
                <li class="control">
                    <label>
                    <input type="radio" name="bill_title"  value="Personal" checked="checked" title="Personal"  class="radio">
                    <label for="bill_title"><?php echo $this->__('Personal');?></label>
                    </label>
                    <label>
                    <input type="radio" name="bill_title"  value="Units" title="Units"  class="radio">
                    <label for="bill_title"><?php echo $this->__('Units');?></label>
                    </label>
                </li>


<!--                    <label><input name="bill_title" type="radio" value="0" checked="checked"/>--><?php //echo $this->__(
//                            'Personal'
//                        );?><!--</label>-->
<!--                    <label><input name="bill_title" type="radio" value="1"/>--><?php //echo $this->__('Units');?><!--</label>-->
                <li class="fields" style="display:none; height: auto;">
                    <div class="field"><label for="bill_company" class="required"><em>*</em><?php echo $this->__('Units Name');?>：</label></div>
                    <div class="input-box">
                        <input name="bill_company" type="text" value="" class="input-text required-entry"/>
                    </div>
<!--                    <div>--><?php //echo $this->__('Units Name');?><!--：<input name="bill_company" type="text" value=""/><span class="required">*</span></div>-->
                    <ul class="bill-tax" style="display:none">
                        <li><strong><?php echo $this->__('Qualification completed VAT invoice invoices');?>：</strong>
                        </li>
                        <li class="fields">
                            <div class="field"><label for="bill_taxpayer_id"
                                                      class="required"><em>*</em><?php echo $this->__(
                                        'Taxpayer identification number'
                                    );?>：</label>

                                <div class="input-box">
                                    <input name="bill_taxpayer_id" type="text" value=""
                                           class="input-text required-entry"/>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field"><label for="bill_address"
                                                      class="required"><em>*</em><?php echo $this->__(
                                        'Registered Address'
                                    );?>：</label>

                                <div class="input-box">
                                    <input name="bill_address" type="text" value=""
                                           class="input-text required-entry"/>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field"><label for="bill_phone"
                                                      class="required"><em>*</em><?php echo $this->__(
                                        'Registered Telephone'
                                    );?>：</label>

                                <div class="input-box">
                                    <input name="bill_phone" type="text" value=""
                                           class="input-text required-entry"/>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field"><label for="bill_bank"
                                                      class="required"><em>*</em><?php echo $this->__(
                                        'Open an account with the bank'
                                    );?>：</label>

                                <div class="input-box">
                                    <input name="bill_bank" type="text" value=""
                                           class="input-text required-entry"/>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field"><label for="bill_account"
                                                      class="required"><em>*</em><?php echo $this->__(
                                        'Bank account'
                                    );?>：</label>

                                <div class="input-box">
                                    <input name="bill_account" type="text" value=""
                                           class="input-text required-entry"/>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="fields" style="height: auto;"><span class="label"><?php echo $this->__('Invoice Content');?>
                        ：</span>
                    <li class="control">
                    <label>
                        <input type="radio" name="bill_content"  value="Detail" checked="checked" title="Detail"  class="radio">
                        <label for="bill_content"><?php echo $this->__('Detail');?></label>
                    </label>


                    <label>
                        <input name="bill_content" type="radio" value="Office Supplies"/>
                        &nbsp;<?php echo $this->__('Office Supplies');?>
                    </label>
                    <label>
                        <input name="bill_content" type="radio" value="Computer Accessories"/>
                        &nbsp;<?php echo $this->__('Computer Accessories');?>
                    </label>
                    <label>
                        <input name="bill_content" type="radio" value="Consumable"/>
                        &nbsp;<?php echo $this->__('Consumable');?>
                    </label>

                    </li>
            </ul>
        </form>
        <dl id="bill-text"></dl>
    </div>
</div>

<div class="buttons-set" id="fapiao-buttons-container">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="fapiao.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="fapiao-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
</div>

<script type="text/javascript">
    //<![CDATA[
    var billEditTag = jQuery('#bill-edit').hide();
    var billTextTag = jQuery('#bill-text');
    var billFormTag = jQuery('#bill-form');
    var billSwitch = jQuery ('#bill-switch');
    var hasInvoice = jQuery('#need_invoice');

    billSwitch.change(function () {
        if (jQuery(this).attr('checked')) {

            hasInvoice.val('1');
            billFormTag.show();
            billTextTag.empty();
        } else {
            hasInvoice.val('0');
            billFormTag.hide();
        }
    }).trigger('change');

    billEditTag.click(function () {
        jQuery(this).hide();
        billSwitch.attr('checked', 'checked').trigger('change');
    });

    billFormTag.find('input[name="bill_title"]').change(function () {
        if (jQuery(this).val() == 'Personal') {
            billFormTag.find('input[name="bill_company"]').parent().parent().hide();
        } else {
            billFormTag.find('input[name="bill_company"]').parent().parent().show();
            jQuery('.bill-tax').hide();
        }
    });

    billFormTag.find('input[name="bill_type"]').change(function () {
        if (jQuery(this).val() == 'VAT Invoice') {
            billFormTag.find('input[name="bill_title"][value="Personal"]').parent('label').hide();
            billFormTag.find('input[name="bill_title"][value="Units"]').attr('checked', 'checked').trigger('change');
            billFormTag.find('input[name="bill_content"][value!="Detail"]').parent('label').hide();
            billFormTag.find('input[name="bill_content"][value="Detail"]').attr('checked', 'checked');
            jQuery('.bill-tax').show();
        } else {
            billFormTag.find('input[name="bill_content"][value!="Detail"]').parent('label').show();
            billFormTag.find('input[name="bill_title"][value="Personal"]').parent('label').show();
            jQuery('.bill-tax').hide();
        }
    });


    billFormTag.submit(function () {
        $this = jQuery(this);
        var flag = true;
        $this.find('input:visible').each(function () {
            var pompt = jQuery(this).parent().find('.error');
            if (jQuery(this).val() == "") {
                var html = '<span class="error"><?php echo Mage::helper('core')->__('Required Fields');?></span>';
                if (pompt.length) {
                    pompt.html(html);
                } else {
                    jQuery(this).parent().append(html);
                }
                flag = false;
            } else {
                pompt.empty();
            }
        });

        if (flag) {
            var params = [];
            $this.find('input:visible').each(function () {
                params.push(jQuery(this).serialize());
            });
            jQuery.post("<?php echo $this->getUrl('*/*/saveBill'); ?>", params.join('&'), function (data) {
                if (data) {
                    data = jQuery.parseJSON(data);
                } else {
                    data = {};
                }
                if (data.error) {
                    if (data.error_messages) {
                        alert(data.error_messages);
                    }
                    else if (data.message) {
                        alert(data.message);
                    }
                    else {
                        alert(data.error);
                    }
                } else {
                    billFormTag.hide();
                    billEditTag.show();

                    var html = '';
                    $this.find("ul li").each(function () {
                        var label = jQuery(this).find('span[class="label"]').text();
                        var text = jQuery(this).find("input:checked").parent('label').text();
                        if (label && text) {
                            html += '<dt>' + label + '</dt>';
                            html += '<dd>' + text + '</dd>';
                        }
                    });
                    billTextTag.html(html);
                }
            });
        }
        return false;
    });


    var Fapiao = Class.create();
    Fapiao.prototype = {
        initialize: function(form, saveUrl){
            this.form = form;
            if ($(this.form)) {
                $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
            }
            this.saveUrl = saveUrl;
            this.onSave = this.nextStep.bindAsEventListener(this);
            this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
        },

        save: function(){
            if (checkout.loadWaiting!=false) return;

            var validator = new Validation(this.form);
            if (validator.validate()) {

                checkout.setLoadWaiting('fapiao');

                var request = new Ajax.Request(
                    this.saveUrl,
                    {
                        method: 'post',
                        onComplete: this.onComplete,
                        onSuccess: this.onSave,
                        onFailure: checkout.ajaxFailure.bind(checkout),
                        parameters: Form.serialize(this.form)
                    }
                );
            }
        },

        resetLoadWaiting: function(transport){
            checkout.setLoadWaiting(false);
        },

        nextStep: function(transport){
            if (transport && transport.responseText){
                try{
                    response = eval('(' + transport.responseText + ')');
                }
                catch (e) {
                    response = {};
                }
            }

            if (response.error){
                if ((typeof response.message) == 'string') {
                    alert(response.message);
                } else {
                    if (window.billingRegionUpdater) {
                        billingRegionUpdater.update();
                    }

                    alert(response.message.join("\n"));
                }

                return false;
            }

            checkout.setStepResponse(response);
        }
    }

    var fapiao = new Fapiao('bill-form', '<?php echo $this->getUrl('checkout/onepage/saveFaPiao') ?>');

    //]]>
</script>
